### ISSUE TITLE
Wondering about fp_math.c thumb vs arm mode

### ISSUE THREAD

**Issue by dsandber** [AntonioND/ugba-testing#1]
Hi,

I noticed this in your fp_math.c comments:

// Note: This code needs to be compiled to ARM, not Thumb. It is also placed
// in IWRAM for even more speed.

Can you explain why the code needs to be compiled in ARM mode?  I'm using a Cortex-M0 (ARMv6 ) chip.  Is there any problem in having all my code other than this function compiled into thumb mode?

Thanks!

**Comment by AntonioND** [comment]
The CPU in ARM mode has instructions that multiply two 32-bit registers and save the 64-bit output into two 32-bit registers. This takes around 4 cycles in the worst case, if I remember correctly. In Thumb mode, this instruction doesn't exist. The code itself will run, there is no technical problem there, it's just that it will be slower. I haven't checked the exact difference, though, but the equivalent multiplication would be replaced by a function call to the gcc library, which is obviously much slower.

Regarding IWRAM, that's just because this is a really short routine that really benefits from being in an area of fast RAM.

**Comment by dsandber** [comment]
Thanks for the info & quick reply!

According to:

https://en.wikipedia.org/wiki/ARM_Cortex-M#Instruction_sets

The 32 x 32 = 64 bit multiply was added in the Cortex M3, so my chip doesn't have it.  I'm guessing my chip doesn't have "IWRAM" either.

 Sounds like I prob. need to find code that is optimized for the M0, bummer! :)

**Comment by AntonioND** [comment]
Yeah, that's annoying. I mean, there is nothing stopping you from testing the speed of the function by yourself and seeing if it's good enough for whatever you need it. Maybe it's not as bad as I think (I guess you can do a 32 x 32 = 64 in 4 multiplications and some additions). But yeah, the M0 is too simple. If you want something even more optimized it's likely that the accuracy won't be as good. I used 32 x 32 = 64 because it's what allowed me to get enough accuracy (but maybe I could have done in a different way). If you only want to use 32 x 32 = 32, you may need to reduce it to 16 bits.

IWRAM is something specific to the GBA (and I guess some other platforms), not something generic. In the Nintendo DS there is something called ITCM that does the same thing if I remember correctly.
